### ISSUE TITLE
GPU conversion

### ISSUE THREAD

**Issue by vitskvara** [aicenter/ConditionalDists.jl#11]
See https://github.com/aicenter/GenerativeModels.jl/issues/72

I think the issue is in the functor definition. Now we have `CMeanGaussian{V,S,M}`, where `M` is the type of mapping. But consider this:

```julia
julia> m = Dense(3,2)
Dense(3, 2)

julia> typeof(m)
Dense{typeof(identity),Array{Float32,2},Array{Float32,1}}

julia> m = m |> gpu
Dense(3, 2)

julia> typeof(m)
Dense{typeof(identity),CuArray{Float32,2,Nothing},CuArray{Float32,1,Nothing}}
```

Clearly, the type changes when moving to the gpu. However, in the functor redefinition, the type `M` is static.

**Comment by nmheim** [comment]
closed with #12
